import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#006399',
        'on-primary': '#ffffff',
        'primary-container': '#4fb3ff',
        'on-primary-container': '#00436a',
        'primary-fixed': '#cde5ff',
        'primary-fixed-dim': '#95ccff',
        'on-primary-fixed': '#001d32',
        'on-primary-fixed-variant': '#004a75',
        'secondary': '#005db7',
        'on-secondary': '#ffffff',
        'secondary-container': '#64a1ff',
        'on-secondary-container': '#003670',
        'secondary-fixed': '#d6e3ff',
        'secondary-fixed-dim': '#a9c7ff',
        'on-secondary-fixed': '#001b3d',
        'on-secondary-fixed-variant': '#00468c',
        'tertiary': '#7f5600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e39f14',
        'on-tertiary-container': '#583a00',
        'tertiary-fixed': '#ffdeae',
        'tertiary-fixed-dim': '#ffba3f',
        'on-tertiary-fixed': '#281900',
        'on-tertiary-fixed-variant': '#604100',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#006399',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3f4851',
        'on-background': '#191c1e',
        'outline': '#6f7882',
        'outline-variant': '#bfc7d2',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#95ccff',
        'background': '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Manrope"', 'sans-serif'],
        label: ['"Manrope"', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 32px 64px -15px rgba(25, 28, 30, 0.06)',
        'ambient-sm': '0 12px 40px -12px rgba(0, 0, 0, 0.05)',
        'ambient-primary': '0 8px 16px -4px rgba(0, 99, 153, 0.2)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
} satisfies Config
